// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Money_Spending_Tracker.Data;

#nullable disable

namespace Money_Spending_Tracker.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250629162537_HomePageUpdate2")]
    partial class HomePageUpdate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Money_Spending_Tracker.Data.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountIban")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstitutionBic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstitutionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("InstitutionLogo")
                        .HasColumnType("BLOB");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Money_Spending_Tracker.Data.Transaction", b =>
                {
                    b.Property<Guid>("InternalTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalInformation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndToEndId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProprietaryBankTransactionCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PurposeCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemittanceInformationStructured")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TransactionAmount")
                        .HasColumnType("REAL");

                    b.Property<string>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimateCreditor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValueDate")
                        .HasColumnType("TEXT");

                    b.HasKey("InternalTransactionId", "AccountId");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
