// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Money_Spending_Tracker.Data;

#nullable disable

namespace Money_Spending_Tracker.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251116130645_RemittanceInformationUnstructured")]
    partial class RemittanceInformationUnstructured
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Money_Spending_Tracker.Data.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountIban")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstitutionBic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstitutionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("InstitutionLogo")
                        .HasColumnType("BLOB");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Money_Spending_Tracker.Data.JobLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorStackTrace")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JobLogs");
                });

            modelBuilder.Entity("Money_Spending_Tracker.Data.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Money_Spending_Tracker.Data.TagNegativeEmbedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("TagNegativeEmbeddings");
                });

            modelBuilder.Entity("Money_Spending_Tracker.Data.Transaction", b =>
                {
                    b.Property<Guid>("InternalTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalInformation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditorName")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("BLOB");

                    b.Property<string>("EndToEndId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryReference")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProprietaryBankTransactionCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("PurposeCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemittanceInformationStructured")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemittanceInformationUnstructured")
                        .HasColumnType("TEXT");

                    b.Property<double>("TransactionAmount")
                        .HasColumnType("REAL");

                    b.Property<string>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimateCreditor")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValueDate")
                        .HasColumnType("TEXT");

                    b.HasKey("InternalTransactionId", "AccountId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Money_Spending_Tracker.Data.TransactionTag", b =>
                {
                    b.Property<Guid>("InternalTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaggedBy")
                        .HasColumnType("INTEGER");

                    b.HasKey("InternalTransactionId", "AccountId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TransactionTags");
                });

            modelBuilder.Entity("Money_Spending_Tracker.Data.TagNegativeEmbedding", b =>
                {
                    b.HasOne("Money_Spending_Tracker.Data.Tag", "Tag")
                        .WithMany("NegativeEmbeddings")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Money_Spending_Tracker.Data.TransactionTag", b =>
                {
                    b.HasOne("Money_Spending_Tracker.Data.Tag", "Tag")
                        .WithMany("TransactionTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Money_Spending_Tracker.Data.Transaction", "Transaction")
                        .WithMany("TransactionTags")
                        .HasForeignKey("InternalTransactionId", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Money_Spending_Tracker.Data.Tag", b =>
                {
                    b.Navigation("NegativeEmbeddings");

                    b.Navigation("TransactionTags");
                });

            modelBuilder.Entity("Money_Spending_Tracker.Data.Transaction", b =>
                {
                    b.Navigation("TransactionTags");
                });
#pragma warning restore 612, 618
        }
    }
}
