// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Money_Spending_Tracker.Data;

#nullable disable

namespace Money_Spending_Tracker.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Money_Spending_Tracker.Data.Transaction", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalInformation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditorAgent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DebtorAgent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndToEndId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalTransactionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProprietaryBankTransactionCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PurposeCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemittanceInformationStructured")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TransactionAmount")
                        .HasColumnType("REAL");

                    b.Property<string>("UltimateCreditor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValueDate")
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
